name: remote ssh deplyment
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        env:
          RUST_LOG: info
          DB_URL: ${{ secrets.DB_URL }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            RUST_LOG=info
            ps -a
            cd e-commerce
            git pull
            ls -la
            cd frontend
            npm install
            npm run build
            cd ../backend
            cargo build --release
            DB_URL=${{ secrets.DB_URL }} RUST_LOG=info ./target/release/backend > ../../rust-log.03-02-2021.log &
            ps aux | grep g13
            exit
