name: remote ssh deplyment
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            RUST_LOG=info
            ps -a
            cd e-commerce
            git pull
            ls -la
            cd frontend
            npm install
            npm run build
            cd ../backend-rust
            cargo build --release
            ./target/release/backend-rust > rust-log.13-01-2021.log &
            ps aux | grep g13
